language: php

sudo: false

matrix:
    include:
        - php: 7.0
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7.0

before_install:
    - composer self-update

install:
    - composer update $COMPOSER_FLAGS

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --verbose
