language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo:
  false

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --prefer-dist update

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --verbose
