language: php

sudo: false

matrix:
    include:
        - php: 7.0
          env: SYMFONY_VERSION='2.7.*'
        - php: 7.0
          env: SYMFONY_VERSION='2.8.*'
        - php: 7.0
          env: SYMFONY_VERSION='3.2.*'

before_install:
    - composer self-update
    - composer --no-update require symfony/symfony:${SYMFONY_VERSION}

install: composer update

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --verbose
