language: php

matrix:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: 7.3

install:
    - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpspec run -f pretty
  - vendor/bin/phpstan analyze --level 5
  - vendor/bin/behat --no-snippets --verbose
