language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --prefer-source update

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --verbose
